name: 'ASCII reply'
description: |
  Replies back to an issue comment with ASCII art text.
  Can be restricted to a 'command' (e.g. /ascii <text>). The command part will be removed.
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
branding:
  icon: 'edit-3'  
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.repo-token }}
