name: Pong

on: [pull_request, issues]

jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/first-interaction@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     issue-message: 'Message that will be displayed on users'' first issue'
    #     pr-message: 'Message that will be displayed on users'' first pr'
    - uses: ../actions/reply
      with:
        who-to-greet: 'Mona the Octocat'
    # - run: sudo apt-get install -y tree
    # - run: tree .
    # - run: tree /home/runner/work/ghapg/.github