name: Pong

on:
  issue_comment:
    types: [created]

jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/reply
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}