name: Pong

on: [pull_request, issues]

jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - uses: actions/first-interaction@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     issue-message: 'Message that will be displayed on users'' first issue'
    #     pr-message: 'Message that will be displayed on users'' first pr'
    - uses: ./.github/actions/reply
      # with:
      #   who-to-greet: 'Mona the Octocat'
    # - run: sudo apt-get install -y tree
    # - run: tree .
    # - run: tree /home/runner/work/ghapg/.github
    # - run: echo "The previous action was run at ${{ steps.hello.outputs.time }}"
    # - id: some_step
    #   run: |
    #     echo ::set-output name=greeting::Hello
    #     echo ::set-env    name=WHO::World
    # - run: |
    #     echo ${{ steps.some_step.outputs.greeting }} $WHO!