name: Pong

on:
  issue_comment:
    types: [created]

jobs:
  pong-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./reply-docker
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  pong-docker-hub:
    steps:
    - uses: docker://pndurette/reply-docker:latest
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  pong-nodejs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./reply-nodejs
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}